{% set name = "neutronics_material_maker" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 693fc24251c0b7e6ee9e6ef16274647efe3c53a41f5002a0f62ee90a31133160

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - openmc
    - coolprop
    - asteval

test:
  imports:
    - neutronics_material_maker

about:
  home: https://github.com/ukaea/neutronics_material_maker
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A tool for making parametric material cards for use in neutronics codes.

  description: |
    The aim of this project is to facilitate the creation of materials
    for use in neutronics codes such as OpenMC, Serpent, MCNP and Fispact.
  doc_url: neutronics-material-maker.readthedocs.io/
  dev_url: https://github.com/ukaea/neutronics_material_maker

extra:
  recipe-maintainers:
    - shimwell
